# Generated by Django 5.2.5 on 2025-08-18 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for project cards', max_length=300)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('live_url', models.URLField(blank=True, help_text='Live project URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or image', null=True, upload_to='projects/')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list of technologies used', max_length=500)),
                ('featured', models.BooleanField(default=False, help_text='Show this project prominently')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
